amqp:
  admin:
    auto-create: false
  host: ${amqp.host}
  port: ${amqp.port}
  username: ${amqp.username}
  password: ${amqp.password}


mysql:
  username: ${mysql.username}
  password: ${mysql.password}
  schema: ${mysql.schema}
  url: ${mysql.url}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none